services:
  time-until-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: time-until-app:latest
    container_name: time-until-countdown
    ports:
      - "4201:4200"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:4200",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
